apiVersion: apps/v1
kind: Deployment
metadata:
  name: loopback-deployment
spec:
  selector:
    matchLabels:
      app: loopback
  replicas: 1 
  template:
    metadata:
      labels:
        app: loopback
    spec:
      containers:
      - name: loopback
        image: deepanshu24saini/testing-img
        ports:
        - containerPort: 8080
