
apiVersion: v1
kind: Service
metadata:
  name: loopback-service
  labels:
    app: loopback
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: loopback
